In [ ]:
import numpy as np

In [ ]:
# Create an array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)


[1 2 3 4 5]


In [ ]:
# Create a 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)


[[1 2 3]
 [4 5 6]]


In [ ]:
# Create an array of zeros
zeros = np.zeros((3, 3))
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Create an array of ones
ones = np.ones((2, 4))
print(ones)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Create an array of random numbers
random_arr = np.random.rand(3, 3)
print(random_arr)

[[0.41088927 0.50464284 0.18182417]
 [0.2749521  0.35929297 0.561526  ]
 [0.05947655 0.05342476 0.71187154]]


In [ ]:
# Create an array with a range of values
range_arr = np.arange(0, 10, 2)
print(range_arr)


[0 2 4 6 8]


In [ ]:
# Create an array with evenly spaced values
lin_space_arr = np.linspace(0, 10, 5)
print(lin_space_arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 4, 5, 6])

# Element-wise operations
arr3 = arr1 + arr2
arr4 = arr1 * 2
print(arr3)
print(arr4)

[ 3  5  7  9 11]
[ 2  4  6  8 10]


In [ ]:
# Matrix multiplication
mat_mul = np.dot(arr2, arr2.T)
print(mat_mul)

90


In [ ]:
# Sum, min, max, mean
total = arr1.sum()
min_val = arr2.min()
max_val = arr2.max()
mean_val = arr2.mean()

print(total)
print(min_val)
print(max_val)
print(mean_val)


15
2
6
4.0


In [ ]:
# Reshape array
reshaped_arr = arr1.reshape(5, 1)
print(reshaped_arr)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
# Transpose array
transposed_arr = arr2.T
print(transposed_arr)

[2 3 4 5 6]


In [ ]:
# Concatenate arrays
concatenated_arr = np.concatenate((arr1, arr2.flatten()))
print(concatenated_arr)


[1 2 3 4 5 2 3 4 5 6]


In [ ]:
# Split array
split_arr = np.split(arr1, 5)
print(split_arr)

[array([1]), array([2]), array([3]), array([4]), array([5])]


In [ ]:
# Trigonometric functions
sin_arr = np.sin(arr1)
print(sin_arr)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
# Exponential and logarithmic functions
exp_arr = np.exp(arr1)
log_arr = np.log(arr1)
print(exp_arr)
print(log_arr)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
# Statistical functions
std_dev = np.std(arr2)
variance = np.var(arr2)
print(std_dev)
print(variance)

1.4142135623730951
2.0


In [ ]:
# Generate random numbers
rand_int = np.random.randint(1, 10)
print(rand_int)
rand_uniform = np.random.rand(3, 3)
print(rand_uniform)

2
[[0.94538356 0.29803952 0.78155665]
 [0.03520118 0.7840017  0.79141054]
 [0.20935633 0.385664   0.24254967]]
